services:
  main:
    build:
      context: ./service-main/
      dockerfile: Dockerfile
      tags:
        - main:latest
    ports:
      - 5000:5000
    environment:
      - MONGO_USER=mongo
      - MONGO_PASSWORD=password
      - MONGO_HOST=mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongo
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo
